version: '3.7'
services:
    web:
        build: .
        command: gunicorn bookstore.wsgi -b 0.0.0.0:8000
        environment: 
            - SECRET_KEY=b*i30c8((!ulrt02)bo74pg%agdvf_5%+(r(ji_2zc^1#%ldb)
            - DEBUG=1
            - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51Kyt0BHkaI7wTr3KjFD6uidGuzlMaMiaX3wxJ7DBOSNGcPTvSVH9xBpWjbVsFYXvIELntoardvHck2O6f14k3Klo008voNP8TW
            - STRIPE_TEST_SECRET_KEY=sk_test_51Kyt0BHkaI7wTr3KDged4Vls7GTiCTx6X6EbIpEeNEu4lcPwfTjeSY00nb2HKXhE21FkY6QxJ4DrJVAzuoZCad1o00r5OQWcFc
            - ENVIRONMENT=development
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            POSTGRES_PASSWORD: 'postgres'
volumes: 
    postgres_data:
